repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [ "--baseline", ".secrets.baseline" ]
        additional_dependencies: [ 'gibberish-detector' ]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.387
    hooks:
      - id: pyright