# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

container_scanning:
  stage: container_test
  variables:
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "false"
    CS_IMAGE: $CI_REGISTRY_IMAGE:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'