.lint:
  extends: .poetry
  stage: lint
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null'
      changes:
        - app/**/*

ruff-lint:
  extends: .lint
  script:
    - ruff check --target-version $PYTHON_VERSION .
  parallel:
    matrix:
      - PYTHON_VERSION: [ "py39", "py310", "py311", "py312" ]

pyright-lint:
  extends: .lint
  script:
    - pyright --pythonversion $PYTHON_VERSION ./
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.9", "3.10", "3.11", "3.12" ]

docker-lint:
  stage: lint
  image: hadolint/hadolint:latest-alpine
  script:
    - find . \( -name 'Dockerfile' -o -name 'gunicorn.Dockerfile' \) -exec hadolint --no-fail -f gitlab_codeclimate {} + > docker-lint.json
  artifacts:
    name: "$CI_JOB_NAME artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    when: always
    reports:
      codequality:
        - docker-lint.json
  interruptible: true
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null'
      changes:
        - app/**/*
        - Dockerfile
        - gunicorn.Dockerfile