include:
  - component: $CI_SERVER_FQDN/components/secret-detection/secret-detection@1.1.2
    inputs:
      stage: secret_detection

secret_detection:
  script:
    - /analyzer run # 탐지 (gitleaks.toml 참고) 실행 && gl.. jsno 파일로 결과 출력
    - cat gl-secret-detection-report.json # 탐지 결과 파일 로그로 출력, vulnerabilities:list 가 empty 면 문제 없음
    - |
      if ! cat gl-secret-detection-report.json | grep -oE "\"vulnerabilities\":\[\]" > /dev/null; then
        echo "Error: Secret leak detected!"
        exit 1
      fi