include:
  - template: Security/SAST.gitlab-ci.yml

.unit-test:
  extends: .poetry
  stage: test
  script:
    - |
      set -o allexport
      source .env
      VERSION=${MAJOR_VERSION}.$(date +'%y%m.%d')-${STATUS}-$CI_COMMIT_SHORT_SHA
      set +o allexport
    - BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')
    - export PYTHONPATH=./app
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junitxml=report.xml -v tests
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null'
      changes:
        - app/**/*

pytest-39:
  extends: .unit-test
  image: python:3.9-slim
pytest-310:
  extends: .unit-test
  image: python:3.10-slim
pytest-311:
  extends: .unit-test
  image: python:3.11-slim
pytest-312:
  extends: .unit-test
  image: python:3.12-slim

semgrep-sast:
  stage: test
  rules:
    - if: '$CI_MERGE_REQUEST_ID == null'
      changes:
        - app/**/*